In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('train.txt',sep = ';',header = None,names = ['text','emotion'])

In [4]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [5]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [7]:
unique_emotions = df['emotion'].unique()
unique_emotions

<ArrowStringArray>
['sadness', 'anger', 'love', 'surprise', 'fear', 'joy']
Length: 6, dtype: str

In [8]:
emotion_numbers = {}
i=0
for emo in unique_emotions:
    emotion_numbers[emo] = i
    i +=1

df["emotion"] = df["emotion"].map(emotion_numbers)

In [9]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [10]:
df['text'] = df['text'].apply(lambda x: x.lower())

## Remove puncuation
- Input: remove_punc("Hello, world! How are you?")
- Output: Hello world How are you

In [14]:
import string

def remove_punc(txt):
  # print(txt.translate(str.maketrans('','',string.punctuation)))
  return txt.translate(str.maketrans('','',string.punctuation))

In [15]:
df['text'] = df['text'].apply(remove_punc)

In [16]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [17]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [19]:
%pip install nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (from nltk) (8.3.2)
Requirement already satisfied: joblib in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (from nltk) (2026.3.32)
Requirement already satisfied: tqdm in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.6 MB 1.1 MB/s eta 0:00:01
   ------------- -------------------------- 0.5/1.6 MB 1.1 MB/s eta 0:00:01
   -------------------- ------------------- 0.8/1.6 MB 799.1 kB/s eta 0:00:01
   -------------------- ------------------- 0.8/1.6 MB 799.1 kB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.6 MB 728.2 kB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.6 MB 728.2 kB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 791.7 kB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 852.7 kB/s eta 0:00:00
Installing collected packages: nltk
Successfully installed nltk-3.9.4
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~lotly (C:\Users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (C:\Users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (C:\Users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\Lib\site-packages)

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [21]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sunnykumar.bhakta\AppData\Roaming\nltk_data..
[nltk_data]     .
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sunnykumar.bhakta\AppData\Roaming\nltk_data..
[nltk_data]     .
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [22]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [23]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [24]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [25]:
df['text'] = df['text'].apply(remove)

In [26]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [27]:


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [33]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)

MultinomialNB()

In [34]:
pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))
pred_bow

0.768125

array([0, 5, 0, ..., 5, 5, 0], shape=(3200,))

In [30]:
X_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 26936 stored elements and shape (3200, 13361)>

In [32]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [35]:
y_pred = nb2_model.predict(X_test_tfidf)
print(accuracy_score(y_test, y_pred))

0.6609375

In [36]:
from sklearn.linear_model import LogisticRegression

In [37]:
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [38]:
log_pred = logistic_model.predict(X_test_tfidf)
print(accuracy_score(y_test,log_pred ))

0.8628125